### ISSUE TITLE
Run the GHA with cron

### ISSUE THREAD

**Issue by matt-dray** [matt-dray/rostrum-blog#64]
Normal flow: write new post, push it, Netlify publishes.

But the GHA might scrape the rostum.blog archive page faster than Netlify can re-serve it with the new post, so the README won't be up to date.

Could run it every day at midnight, or maybe there's a way to run an Action e.g. 30mins after a push to allow time for the new post to show up on the blog.

**Comment by matt-dray** [comment]
As per https://github.com/matt-dray/matt-dray/blob/master/.github/workflows/blog-post-workflow.yml

```
on:
  schedule:
    # Runs every day at midnight
    - cron: '0 0 * * *'
```
